# Generated by Django 4.1 on 2023-03-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_coursestudent_enrollment_date_teacher_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
