version: '3.8'

services:
  web:
    container_name: django_web
    build: .
    image: sdi/django_backend
    command: gunicorn django_example.wsgi --workers 4 --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: django_db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses

volumes:
  postgres_data: